Add cron jobs section
Brunty/awesome-checker-services pull request #52
Opened 2020-10-16 10:32 UTC by MadamaMktg

Added cron jobs section :)

2020-10-16 14:30 UTC, Brunty requested changes

2020-10-16 14:30 UTC, Brunty commented on README.md
> +| https://healthchecks.io/ | Simple and Effective Cron Job Monitoring. | Free |
Can these be put into alphabetical order? Both sections and links within them should be. Thanks!

https://github.com/Brunty/awesome-checker-services/blob/master/CONTRIBUTING.md#getting-started

2020-10-16 14:30 UTC, Brunty commented on README.md
> +## Cron Jobs 🌎
Can the icon be updated to match the one in the list above? ⚡

2020-10-17 16:35 UTC, MadamaMktg commented
Updated the domain order to be alphabetical and also updated the icon. Thank you! 👍

2020-10-18 16:35 UTC, Brunty approved these changes

2020-10-18 16:35 UTC, Brunty commented
Thank you for this! :)

2020-10-18 16:35 UTC, merged